# Site settings
title: 程’s Blog
header-img: img/home-bg.jpg
email: 421579739@qq.com
description: "生于忧患，死于安乐"
baseurl: "/blog"
url: "http://zycczy.github.io"
twitter_username: zycczy
github_username:  zycczy
facebook_username: zycczy

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
